### ISSUE TITLE
License doesn't match one listed on website

### ISSUE THREAD

**Issue by ataulm** [jellow-aac/Jellow-Communicator#12]
Hi, what's the licence for this project. The website lists cc non-commercial sharealike:

![screenshot_20180615-170635](https://user-images.githubusercontent.com/2678555/41478166-9f3b776c-70be-11e8-9aeb-82c0399e32aa.png)

but the readme shows BSD. Is the website referring to something else?

**Comment by rahuljidgedev** [comment]
Thank you ataulm for lettings us know about this issue. We have corrected the ambiguity. Please take a look.
