### ISSUE TITLE
Reduce the image chooser popup text size and horizontal padding.

### ISSUE THREAD

**Issue by rahuljidgedev** [jellow-aac/Jellow-Communicator#55]
- The popup looks big in size as compared to other screen sizes.
- Reduce the text size the same as button "Save" button
This screenshot from the phone.
![Screenshot_20200210-121846](https://user-images.githubusercontent.com/36405481/74127293-3fa96b00-4c00-11ea-989a-bebd6565cc70.png)

This screenshot from the tablet.
![Screenshot_2020-02-10-12-21-48-613](https://user-images.githubusercontent.com/36405481/74127292-3e783e00-4c00-11ea-9589-215d98770534.jpeg)

**Comment by ayaz-alam** [comment]
7'& 8' and 10 requires larger text

**Comment by rahuljidgedev** [comment]
- The changes are perfect for the mobile screen size. Increase width of popup for mobile screen sizes by 2dp or 4dp.
- Revert the previous sizes for 7', 8' & 10'  devices.
