### ISSUE TITLE
Change Text color to 80 percent black.

### ISSUE THREAD

**Issue by rahuljidgedev** [jellow-aac/Jellow-Communicator#57]
- The Text color right now is pure black. Change it to 80 % black
- The color should change at the actionbar title of Select icons, Add/Edit icons, Board Home screens.

- The dialog box which appears at Select Icons screen. Check the text uses "EkMukta-Bold" font and correct it if not.
- Check the text color of "Select All (4)" on the same screen. Either text "(4)" has a different color or "Select All". Make both of them use 80 percent black and "Ekmukta-Regular" font.

![Screenshot_2020-02-10-12-54-16-361](https://user-images.githubusercontent.com/36405481/74129139-d2e49f80-4c04-11ea-9cbb-db6d116df261.jpeg)

**Comment by ayaz-alam** [comment]
I am not assigning color of the action bar in my code, it should reflect automatically by the style file that we've used. I've used _setupToolBar_ in the activity to initialize the action bar.

**Comment by rahuljidgedev** [comment]
Please change the dialog text color.

**Comment by ayaz-alam** [comment]
I've changed it to 80% black already

**Comment by ayaz-alam** [comment]
Changed the color to pick up the style

**Comment by rahuljidgedev** [comment]
- Change the text style the same as on MainActivity's below text.
