### ISSUE TITLE
Adjust components at Add/Edit icons dialog.

### ISSUE THREAD

**Issue by rahuljidgedev** [jellow-aac/Jellow-Communicator#59]
- Increase the text size of the dialog title. The title text size should be matched with the button's text size on the same layout.
- Align the add & minus buttons to the center of EditText.
- Add spacing between add & minus buttons same as expressive icons and EditText
- Increase the dialog size horizontally.
The above changes should reflect on all screen sizes.
Currently, the layout looks like as below: (phone, 7, 8, 10 respectively)

![Screenshot_20200210-150627](https://user-images.githubusercontent.com/36405481/74139867-1b5a8800-4c1a-11ea-90e7-8a44be2d3e88.png)
![Screenshot_2020-02-10-15-11-19](https://user-images.githubusercontent.com/36405481/74139947-33320c00-4c1a-11ea-9da7-8ccdc2437893.png)
![Screenshot_20200210-150629_Jellow](https://user-images.githubusercontent.com/36405481/74139962-3a591a00-4c1a-11ea-8fb3-99703f2ea11c.jpg)
![Screenshot_2020-02-10-15-06-24-954](https://user-images.githubusercontent.com/36405481/74139976-3fb66480-4c1a-11ea-98c0-86beb50d9735.jpeg)

**Comment by ayaz-alam** [comment]
Increase the size of the icon

**Comment by rahuljidgedev** [comment]
- Increase the '+' & '-' icon size by 2dp or 4 dp.
