### ISSUE TITLE
Select icons screen responds very slow.

### ISSUE THREAD

**Issue by rahuljidgedev** [jellow-aac/Jellow-Communicator#62]
When I select any category on the "Select Icons" screen, the app takes a big chunk of time to populate the relevant category icons to the recycler view.

**Comment by ayaz-alam** [comment]
This is a performance issue. I'll need some time to figure out how to improve this thing.

**Comment by rahuljidgedev** [comment]
How can you the time on a date?

**Comment by ayaz-alam** [comment]
Can you please share the details of the device? Is it happening in high-end devices too?
