### ISSUE TITLE
Improve the Add/Edit Icons screen Recycler item UI to make it more clean and simpler.

### ISSUE THREAD

**Issue by rahuljidgedev** [jellow-aac/Jellow-Communicator#63]
The current UI looks too much of clutter. Can we make simpler with the same functionality?

![Screenshot_2020-02-10-13-05-48-522](https://user-images.githubusercontent.com/36405481/74143328-9e7edc80-4c20-11ea-8677-015a40f70245.jpeg)

![Screenshot_20200210-130823](https://user-images.githubusercontent.com/36405481/74143326-9c1c8280-4c20-11ea-8441-88ab3f154df9.png)

**Comment by ayaz-alam** [comment]
What are your suggestions?

**Comment by rahuljidgedev** [comment]
Please ignore the issue. We are working on it.
